
(function($){this.init=function(){this.seo();};this.seo=function(e){};this.init();})(jQuery);
;;;
(function($){this.init=function(){this.headerAlerts();};this.headerAlerts=function(e){if(Modernizr.localstorage){$(".header-alert").each(function(){if(localStorage["HeaderAlert-"+$(this).attr("id").replace(" ","")]==null){localStorage["HeaderAlert-"+$(this).attr("id").replace(" ","")]="no";}
if(localStorage["HeaderAlert-"+$(this).attr("id").replace(" ","")]=="no"){$(this).show();}
$(".header-alert .dismiss").click(function(){$(this).parent(".header-alert").slideUp().remove();localStorage["HeaderAlert-"+$(this).parents(".header-alert").attr("id").replace(" ","")]="yes";});});}
else{$(".header-alert").show();$(".header-alert .dismiss").hide();}};this.init();})(jQuery);
;;;
(function($,window,document){"use strict";var pluginName="accessibleMegaMenu",defaults={uuidPrefix:"accessible-megamenu",menuClass:"accessible-megamenu",topNavItemClass:"accessible-megamenu-top-nav-item",panelClass:"accessible-megamenu-panel",panelGroupClass:"accessible-megamenu-panel-group",hoverClass:"hover",focusClass:"focus",openClass:"open"},Keyboard={BACKSPACE:8,COMMA:188,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,LEFT:37,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SPACE:32,TAB:9,UP:38,keyMap:{48:"0",49:"1",50:"2",51:"3",52:"4",53:"5",54:"6",55:"7",56:"8",57:"9",59:";",65:"a",66:"b",67:"c",68:"d",69:"e",70:"f",71:"g",72:"h",73:"i",74:"j",75:"k",76:"l",77:"m",78:"n",79:"o",80:"p",81:"q",82:"r",83:"s",84:"t",85:"u",86:"v",87:"w",88:"x",89:"y",90:"z",96:"0",97:"1",98:"2",99:"3",100:"4",101:"5",102:"6",103:"7",104:"8",105:"9",190:"."}};function AccessibleMegaMenu(element,options){this.element=element;this.settings=$.extend({},defaults,options);this._defaults=defaults;this._name=pluginName;this.mouseTimeoutID=null;this.focusTimeoutID=null;this.mouseFocused=false;this.justFocused=false;this.init();}
AccessibleMegaMenu.prototype=(function(){var uuid=0,keydownTimeoutDuration=1000,keydownSearchString="",isTouch=typeof window.hasOwnProperty==="function"&&!!window.hasOwnProperty("ontouchstart"),_getPlugin,_addUniqueId,_togglePanel,_clickHandler,_clickOutsideHandler,_DOMAttrModifiedHandler,_focusInHandler,_focusOutHandler,_keyDownHandler,_mouseDownHandler,_mouseOverHandler,_mouseOutHandler,_toggleExpandedEventHandlers;_getPlugin=function(element){return $(element).closest(':data(plugin_'+pluginName+')').data("plugin_"+pluginName);};_addUniqueId=function(element){element=$(element);var settings=this.settings;if(!element.attr("id")){element.attr("id",settings.uuidPrefix+"-"+new Date().getTime()+"-"+(++uuid));}};_togglePanel=function(event,hide){var target=$(event.target),that=this,settings=this.settings,menu=this.menu,topli=target.closest('.'+settings.topNavItemClass),panel=target.hasClass(settings.panelClass)?target:target.closest('.'+settings.panelClass),newfocus;_toggleExpandedEventHandlers.call(this,true);if(hide){topli=menu.find('.'+settings.topNavItemClass+' .'+settings.openClass+':first').closest('.'+settings.topNavItemClass);if(!(topli.is(event.relatedTarget)||topli.has(event.relatedTarget).length>0)){if((event.type==='mouseout'||event.type==='focusout')&&topli.has(document.activeElement).length>0){return;}
topli.find('[aria-expanded]').attr('aria-expanded','false').removeClass(settings.openClass).filter('.'+settings.panelClass).attr('aria-hidden','true');if((event.type==='keydown'&&event.keyCode===Keyboard.ESCAPE)||event.type==='DOMAttrModified'){newfocus=topli.find(':tabbable:first');setTimeout(function(){menu.find('[aria-expanded].'+that.settings.panelClass).off('DOMAttrModified.accessible-megamenu');newfocus.focus();that.justFocused=false;},99);}}else if(topli.length===0){menu.find('[aria-expanded=true]').attr('aria-expanded','false').removeClass(settings.openClass).filter('.'+settings.panelClass).attr('aria-hidden','true');}}else{clearTimeout(that.focusTimeoutID);topli.siblings().find('[aria-expanded]').attr('aria-expanded','false').removeClass(settings.openClass).filter('.'+settings.panelClass).attr('aria-hidden','true');topli.find('[aria-expanded]').attr('aria-expanded','true').addClass(settings.openClass).filter('.'+settings.panelClass).attr('aria-hidden','false');if(event.type==='mouseover'&&target.is(':tabbable')&&topli.length===1&&panel.length===0&&menu.has(document.activeElement).length>0){target.focus();that.justFocused=false;}
_toggleExpandedEventHandlers.call(that);}};_clickHandler=function(event){var target=$(event.currentTarget),topli=target.closest('.'+this.settings.topNavItemClass),panel=target.closest('.'+this.settings.panelClass);if(topli.length===1&&panel.length===0&&topli.find('.'+this.settings.panelClass).length===1){if(!target.hasClass(this.settings.openClass)){event.preventDefault();event.stopPropagation();_togglePanel.call(this,event);this.justFocused=false;}else{if(this.justFocused){event.preventDefault();event.stopPropagation();this.justFocused=false;}else if(isTouch){event.preventDefault();event.stopPropagation();_togglePanel.call(this,event,target.hasClass(this.settings.openClass));}}}};_clickOutsideHandler=function(event){if($(event.target).closest(this.menu).length===0){event.preventDefault();event.stopPropagation();_togglePanel.call(this,event,true);}};_DOMAttrModifiedHandler=function(event){if(event.originalEvent.attrName==='aria-expanded'&&event.originalEvent.newValue==='false'&&$(event.target).hasClass(this.settings.openClass)){event.preventDefault();event.stopPropagation();_togglePanel.call(this,event,true);}};_focusInHandler=function(event){clearTimeout(this.focusTimeoutID);var target=$(event.target),panel=target.closest('.'+this.settings.panelClass);target.addClass(this.settings.focusClass).on('click.accessible-megamenu',$.proxy(_clickHandler,this));this.justFocused=!this.mouseFocused;this.mouseFocused=false;if(this.panels.not(panel).filter('.'+this.settings.openClass).length){_togglePanel.call(this,event);}};_focusOutHandler=function(event){this.justFocused=false;var that=this,target=$(event.target),topli=target.closest('.'+this.settings.topNavItemClass),keepOpen=false;target.removeClass(this.settings.focusClass).off('click.accessible-megamenu');if(window.cvox){that.focusTimeoutID=setTimeout(function(){window.cvox.Api.getCurrentNode(function(node){if(topli.has(node).length){clearTimeout(that.focusTimeoutID);}else{that.focusTimeoutID=setTimeout(function(scope,event,hide){_togglePanel.call(scope,event,hide);},275,that,event,true);}});},25);}else{that.focusTimeoutID=setTimeout(function(){_togglePanel.call(that,event,true);},300);}};_keyDownHandler=function(event){var that=(this.constructor===AccessibleMegaMenu)?this:_getPlugin(this),settings=that.settings,target=$($(this).is('.'+settings.hoverClass+':tabbable')?this:event.target),menu=that.menu,topnavitems=that.topnavitems,topli=target.closest('.'+settings.topNavItemClass),tabbables=menu.find(':tabbable'),panel=target.hasClass(settings.panelClass)?target:target.closest('.'+settings.panelClass),panelGroups=panel.find('.'+settings.panelGroupClass),currentPanelGroup=target.closest('.'+settings.panelGroupClass),next,keycode=event.keyCode||event.which,start,i,o,label,found=false,newString=Keyboard.keyMap[event.keyCode]||'',regex,isTopNavItem=(topli.length===1&&panel.length===0);if(target.is("input:focus, select:focus, textarea:focus, button:focus")){return;}
if(target.is('.'+settings.hoverClass+':tabbable')){$('html').off('keydown.accessible-megamenu');}
switch(keycode){case Keyboard.ESCAPE:_togglePanel.call(that,event,true);break;case Keyboard.DOWN:event.preventDefault();if(isTopNavItem){_togglePanel.call(that,event);found=(topli.find('.'+settings.panelClass+' :tabbable:first').focus().length===1);}else{found=(tabbables.filter(':gt('+tabbables.index(target)+'):first').focus().length===1);}
if(!found&&window.opera&&opera.toString()==="[object Opera]"&&(event.ctrlKey||event.metaKey)){tabbables=$(':tabbable');i=tabbables.index(target);found=($(':tabbable:gt('+$(':tabbable').index(target)+'):first').focus().length===1);}
break;case Keyboard.UP:event.preventDefault();if(isTopNavItem&&target.hasClass(settings.openClass)){_togglePanel.call(that,event,true);next=topnavitems.filter(':lt('+topnavitems.index(topli)+'):last');if(next.children('.'+settings.panelClass).length){found=(next.children().attr('aria-expanded','true').addClass(settings.openClass).filter('.'+settings.panelClass).attr('aria-hidden','false').find(':tabbable:last').focus()===1);}}else if(!isTopNavItem){found=(tabbables.filter(':lt('+tabbables.index(target)+'):last').focus().length===1);}
if(!found&&window.opera&&opera.toString()==="[object Opera]"&&(event.ctrlKey||event.metaKey)){tabbables=$(':tabbable');i=tabbables.index(target);found=($(':tabbable:lt('+$(':tabbable').index(target)+'):first').focus().length===1);}
break;case Keyboard.RIGHT:event.preventDefault();if(isTopNavItem){found=(topnavitems.filter(':gt('+topnavitems.index(topli)+'):first').find(':tabbable:first').focus().length===1);}else{if(panelGroups.length&&currentPanelGroup.length){found=(panelGroups.filter(':gt('+panelGroups.index(currentPanelGroup)+'):first').find(':tabbable:first').focus().length===1);}
if(!found){found=(topli.find(':tabbable:first').focus().length===1);}}
break;case Keyboard.LEFT:event.preventDefault();if(isTopNavItem){found=(topnavitems.filter(':lt('+topnavitems.index(topli)+'):last').find(':tabbable:first').focus().length===1);}else{if(panelGroups.length&&currentPanelGroup.length){found=(panelGroups.filter(':lt('+panelGroups.index(currentPanelGroup)+'):last').find(':tabbable:first').focus().length===1);}
if(!found){found=(topli.find(':tabbable:first').focus().length===1);}}
break;case Keyboard.TAB:i=tabbables.index(target);if(event.shiftKey&&isTopNavItem&&target.hasClass(settings.openClass)){_togglePanel.call(that,event,true);next=topnavitems.filter(':lt('+topnavitems.index(topli)+'):last');if(next.children('.'+settings.panelClass).length){found=next.children().attr('aria-expanded','true').addClass(settings.openClass).filter('.'+settings.panelClass).attr('aria-hidden','false').find(':tabbable:last').focus();}}else if(event.shiftKey&&i>0){found=(tabbables.filter(':lt('+i+'):last').focus().length===1);}else if(!event.shiftKey&&i<tabbables.length-1){found=(tabbables.filter(':gt('+i+'):first').focus().length===1);}else if(window.opera&&opera.toString()==="[object Opera]"){tabbables=$(':tabbable');i=tabbables.index(target);if(event.shiftKey){found=($(':tabbable:lt('+$(':tabbable').index(target)+'):last').focus().length===1);}else{found=($(':tabbable:gt('+$(':tabbable').index(target)+'):first').focus().length===1);}}
if(found){event.preventDefault();}
break;case Keyboard.SPACE:if(isTopNavItem){event.preventDefault();_clickHandler.call(that,event);}else{return true;}
break;case Keyboard.ENTER:return true;break;default:clearTimeout(this.keydownTimeoutID);keydownSearchString+=newString!==keydownSearchString?newString:'';if(keydownSearchString.length===0){return;}
this.keydownTimeoutID=setTimeout(function(){keydownSearchString='';},keydownTimeoutDuration);if(isTopNavItem&&!target.hasClass(settings.openClass)){tabbables=tabbables.filter(':not(.'+settings.panelClass+' :tabbable)');}else{tabbables=topli.find(':tabbable');}
if(event.shiftKey){tabbables=$(tabbables.get().reverse());}
for(i=0;i<tabbables.length;i++){o=tabbables.eq(i);if(o.is(target)){start=(keydownSearchString.length===1)?i+1:i;break;}}
regex=new RegExp('^'+keydownSearchString.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,'\\$&'),'i');for(i=start;i<tabbables.length;i++){o=tabbables.eq(i);label=$.trim(o.text());if(regex.test(label)){found=true;o.focus();break;}}
if(!found){for(i=0;i<start;i++){o=tabbables.eq(i);label=$.trim(o.text());if(regex.test(label)){o.focus();break;}}}
break;}
that.justFocused=false;};_mouseDownHandler=function(event){if($(event.target).is(this.settings.panelClass)||$(event.target).closest(":focusable").length){this.mouseFocused=true;}
this.mouseTimeoutID=setTimeout(function(){clearTimeout(this.focusTimeoutID);},1);};_mouseOverHandler=function(event){clearTimeout(this.mouseTimeoutID);$(event.target).addClass(this.settings.hoverClass);_togglePanel.call(this,event);if($(event.target).is(':tabbable')){$('html').on('keydown.accessible-megamenu',$.proxy(_keyDownHandler,event.target));}};_mouseOutHandler=function(event){var that=this;$(event.target).removeClass(that.settings.hoverClass);that.mouseTimeoutID=setTimeout(function(){_togglePanel.call(that,event,true);},250);if($(event.target).is(':tabbable')){$('html').off('keydown.accessible-megamenu');}};_toggleExpandedEventHandlers=function(hide){var menu=this.menu;if(hide){$('html').off('mouseup.outside-accessible-megamenu, touchend.outside-accessible-megamenu, mspointerup.outside-accessible-megamenu,  pointerup.outside-accessible-megamenu');menu.find('[aria-expanded].'+this.settings.panelClass).off('DOMAttrModified.accessible-megamenu');}else{$('html').on('mouseup.outside-accessible-megamenu, touchend.outside-accessible-megamenu, mspointerup.outside-accessible-megamenu,  pointerup.outside-accessible-megamenu',$.proxy(_clickOutsideHandler,this));menu.find('[aria-expanded=true].'+this.settings.panelClass).on('DOMAttrModified.accessible-megamenu',$.proxy(_DOMAttrModifiedHandler,this));}};return{constructor:AccessibleMegaMenu,init:function(){var settings=this.settings,nav=$(this.element),menu=nav.children().first(),topnavitems=menu.children();this.start(settings,nav,menu,topnavitems);},start:function(settings,nav,menu,topnavitems){var that=this;this.settings=settings;this.menu=menu;this.topnavitems=topnavitems;nav.attr("role","navigation");menu.addClass(settings.menuClass);topnavitems.each(function(i,topnavitem){var topnavitemlink,topnavitempanel;topnavitem=$(topnavitem);topnavitem.addClass(settings.topNavItemClass);topnavitemlink=topnavitem.find(":tabbable:first");topnavitempanel=topnavitem.children(":not(:tabbable):last");_addUniqueId.call(that,topnavitemlink);if(topnavitempanel.length){_addUniqueId.call(that,topnavitempanel);topnavitemlink.attr({"aria-haspopup":true,"aria-controls":topnavitempanel.attr("id"),"aria-expanded":false});topnavitempanel.attr({"role":"group","aria-expanded":false,"aria-hidden":true}).addClass(settings.panelClass).not("[aria-labelledby]").attr("aria-labelledby",topnavitemlink.attr("id"));}});this.panels=menu.find("."+settings.panelClass);menu.on("focusin.accessible-megamenu",":focusable, ."+settings.panelClass,$.proxy(_focusInHandler,this)).on("focusout.accessible-megamenu",":focusable, ."+settings.panelClass,$.proxy(_focusOutHandler,this)).on("keydown.accessible-megamenu",$.proxy(_keyDownHandler,this)).on("mouseover.accessible-megamenu",$.proxy(_mouseOverHandler,this)).on("mouseout.accessible-megamenu",$.proxy(_mouseOutHandler,this)).on("mousedown.accessible-megamenu",$.proxy(_mouseDownHandler,this));if(isTouch){menu.on("touchstart.accessible-megamenu",$.proxy(_clickHandler,this));}
menu.find("hr").attr("role","separator");if($(document.activeElement).closest(menu).length){$(document.activeElement).trigger("focusin.accessible-megamenu");}},getDefaults:function(){return this._defaults;},getOption:function(opt){return this.settings[opt];},getAllOptions:function(){return this.settings;},setOption:function(opt,value,reinitialize){this.settings[opt]=value;if(reinitialize){this.init();}}};}());$.fn[pluginName]=function(options){return this.each(function(){if(!$.data(this,"plugin_"+pluginName)){$.data(this,"plugin_"+pluginName,new $.fn[pluginName].AccessibleMegaMenu(this,options));}});};$.fn[pluginName].AccessibleMegaMenu=AccessibleMegaMenu;function visible(element){return $.expr.filters.visible(element)&&!$(element).parents().addBack().filter(function(){return $.css(this,"visibility")==="hidden";}).length;}
function focusable(element,isTabIndexNotNaN){var map,mapName,img,nodeName=element.nodeName.toLowerCase();if("area"===nodeName){map=element.parentNode;mapName=map.name;if(!element.href||!mapName||map.nodeName.toLowerCase()!=="map"){return false;}
img=$("img[usemap=#"+mapName+"]")[0];return!!img&&visible(img);}
return(/input|select|textarea|button|object/.test(nodeName)?!element.disabled:"a"===nodeName?element.href||isTabIndexNotNaN:isTabIndexNotNaN)&&visible(element);}
$.extend($.expr[":"],{data:$.expr.createPseudo?$.expr.createPseudo(function(dataName){return function(elem){return!!$.data(elem,dataName);};}):function(elem,i,match){return!!$.data(elem,match[3]);},focusable:function(element){return focusable(element,!isNaN($.attr(element,"tabindex")));},tabbable:function(element){var tabIndex=$.attr(element,"tabindex"),isTabIndexNaN=isNaN(tabIndex);return(isTabIndexNaN||tabIndex>=0)&&focusable(element,!isTabIndexNaN);}});}(jQuery,window,document));
;;;
(function($){this.init=function(){this.header();this.search();this.mobileNav();};this.header=function(e){if($(".header-search").val()!=""){$(".header-search").siblings("label").hide();}
$(".header-search").focus(function(){$(this).siblings("label").hide();});$(".header-search").blur(function(){if($(this).val()==""){$(this).siblings("label").show();}});$("header .main > nav > ul > li."+$("header").data("active")).addClass("active");$("header .main > nav").accessibleMegaMenu({});};this.search=function(e){$("#header-search-submit").click(function(e){e.preventDefault();searchSubmit($("#header-search-text").val().replace(/[^\w\s]/gi,""));});$("#header-search-text").keydown(function(e){var code=e.keyCode||e.which;if(code==13){e.preventDefault();searchSubmit($("#header-search-text").val().replace(/[^\w\s]/gi,""));}});$("#mobile-search-submit").click(function(e){e.preventDefault();searchSubmit($("#mobile-search-text").val().replace(/[^\w\s]/gi,""));});$("#mobile-search-text").keydown(function(e){var code=e.keyCode||e.which;if(code==13){e.preventDefault();searchSubmit($("#mobile-search-text").val().replace(/[^\w\s]/gi,""));}});};this.searchSubmit=function(searchString){if(searchString==""){}
else{window.location="/search-results?q="+searchString;}};this.mobileNav=function(e){$(".mobile-trigger").click(function(e){if($("body").hasClass("mobile-engaged")==false){$(".mobile-wrapper").animate({left:"-270px"},150);$(".mobile-menu").animate({marginLeft:"-270px"},150,function(){$("body").addClass("mobile-engaged");});}
else{$(".mobile-wrapper").animate({left:0},150);$(".mobile-menu").animate({marginLeft:0},150,function(){$("body").removeClass("mobile-engaged");});}});$(".mobile-menu .sub-menu").parent("li").each(function(e){$(this).addClass("hasChildren").children("a").append("<i class='fa fa-plus'></i><i class='fa fa-minus'></i>");});$(".mobile-menu li").each(function(e){if($(this).children("ul").length>0){$(this).addClass("hasChildren");}});$(".mobile-menu ul li").addClass("level1");$(".mobile-menu ul ul li").removeClass("level1").addClass("level2");$(".mobile-menu ul ul ul li").removeClass("level2").addClass("level3");$(".mobile-menu ul ul ul ul li").removeClass("level3").addClass("level4");$(".mobile-menu a").click(function(e){if($(this).parent("li").hasClass("hasChildren")==true){if($(this).parent().hasClass("open")==false){e.preventDefault();e.stopPropagation();$(this).parents("li").siblings("li.open").children(".sub-menu, ul").slideUp();$(this).parents("li").siblings("li.open").removeClass("open");$(this).siblings(".sub-menu, ul").slideDown();$(this).parent().addClass("open");}}});};this.init();})(jQuery);
;;;
(function($){this.init=function(){this.login();};this.login=function(e){$(".login .trigger").click(function(){$(".login .content").slideToggle(150);$(this).find(".fa").toggle();$(this).children("span").toggle();});};this.init();})(jQuery);
;;;
(function($){this.init=function(){this.footer();};this.footer=function(e){if($("header").data("active")=="investment"){$(".footer-ncua").hide();$(".footer-ehl").hide();}};this.init();})(jQuery);
;;;
(function($){$.EqualHeight=function($element,options){$element.data('EqualHeight',this);this.init=function($element,options){this.options=$.extend({},$.EqualHeight.defaultOptions,options);$(window).load($.proxy(this.resizeElements,this));$(window).resize($.proxy(this.resizeElements,this));};this.resizeElements=function(e){if(!$element.hasClass('equal-height')){if(viewport().width>=1200){if(!$element.hasClass('equal-height-lg')){$element.children().outerHeight('');this.showElement();return;}}else if(viewport().width>=960&&viewport().width<=1199){if(!$element.hasClass('equal-height-md')){$element.children().outerHeight('');this.showElement();return;}}else if(viewport().width>=768&&viewport().width<=959){if(!$element.hasClass('equal-height-sm')){$element.children().outerHeight('');this.showElement();return;}}else if(viewport().width<=767){if(!$element.hasClass('equal-height-xs')){$element.children().outerHeight('');this.showElement();return;}}}
var maxHeight=0;$element.children().height('auto');$element.children().each(function(){maxHeight=($(this).outerHeight()>maxHeight)?$(this).outerHeight():maxHeight;});$element.children().each(function(){$(this).trigger('setting-equal-height');$(this).outerHeight(maxHeight);$(this).trigger('set-equal-height');});this.showElement();};this.showElement=function(e){$element.css('visibility','visible');};this.init($element,options);};$.fn.EqualHeight=(function(options){return this.each(function(){(new $.EqualHeight($(this),options));});});$.EqualHeight.defaultOptions={};$("[class*='equal-height']").EqualHeight();})(jQuery);(function($){$.EqualWidth=function($element,options){$element.data('EqualWidth',this);this.init=function($element,options){this.options=$.extend({},$.EqualWidth.defaultOptions,options);$(window).load($.proxy(this.resizeElements,this));$(window).resize($.proxy(this.resizeElements,this));};this.resizeElements=function(e){if(!$element.hasClass('equal-width')){if(viewport().width>=1200){if(!$element.hasClass('equal-width-lg')){$element.children().width('');this.showElement();return;}}else if(viewport().width>=960&&viewport().width<=1199){if(!$element.hasClass('equal-width-md')){$element.children().width('');this.showElement();return;}}else if(viewport().width>=768&&viewport().width<=959){if(!$element.hasClass('equal-width-sm')){$element.children().width('');this.showElement();return;}}else if(viewport().width<=767){if(!$element.hasClass('equal-width-xs')){$element.children().width('');this.showElement();return;}}}
$element.children().each(function(){$(this).trigger('setting-equal-width');$(this).width('auto');$(this).width(100/$element.children().length+'%');$(this).trigger('set-equal-width');});this.showElement();};this.showElement=function(e){$element.css('visibility','visible');};this.init($element,options);};$.fn.EqualWidth=(function(options){return this.each(function(){(new $.EqualWidth($(this),options));});});$.EqualWidth.defaultOptions={};$("[class*='equal-width']").EqualWidth();})(jQuery);(function($){$.ProportionalWidth=function($element,options){$element.data('ProportionalWidth',this);this.init=function($element,options){this.options=$.extend({},$.ProportionalWidth.defaultOptions,options);$(window).load($.proxy(this.resizeElements,this));$(window).resize($.proxy(this.resizeElements,this));};this.resizeElements=function(e){if(!$element.hasClass('proportional-width')){if(viewport().width>=1200){if(!$element.hasClass('proportional-width-lg')){$element.children().width('');this.showElement();return;}}else if(viewport().width>=960&&viewport().width<=1199){if(!$element.hasClass('proportional-width-md')){$element.children().width('');this.showElement();return;}}else if(viewport().width>=768&&viewport().width<=959){if(!$element.hasClass('proportional-width-sm')){$element.children().width('');this.showElement();return;}}else if(viewport().width<=767){if(!$element.hasClass('proportional-width-xs')){$element.children().width('');this.showElement();return;}}}
var parentWidth=0;var i=0;var itemWidths=new Array();$element.children().each(function(){itemWidths[i]=$(this).width();parentWidth+=$(this).width();i++;});i=0;$element.children().each(function(){$(this).trigger('setting-proportional-width')
$(this).width((itemWidths[i]/parentWidth)*100+'%');$(this).trigger('set-proportional-width')
i++;});this.showElement();};this.showElement=function(e){$element.css('visibility','visible');};this.init($element,options);};$.fn.ProportionalWidth=(function(options){return this.each(function(){(new $.ProportionalWidth($(this),options));});});$.ProportionalWidth.defaultOptions={};$("[class*='proportional-width']").ProportionalWidth();})(jQuery);(function($){$.AutoClone=function($element,options){$element.data('AutoClone',this);this.init=function($element,options){this.options=$.extend({},$.AutoClone.defaultOptions,options);this.cloneElements();};this.cloneElements=function(){var key=$element.data('key');$element.trigger('cloning-from');$("[data-action='clone'][data-key='"+key+"'][data-type='dest']").trigger('cloning-to');$element.clone().appendTo("[data-action='clone'][data-key='"+key+"'][data-type='dest']").prepend('<div></div>').find('> div:first-child').unwrap().remove();$element.trigger('cloned-from');$("[data-action='clone'][data-key='"+key+"'][data-type='dest']").trigger('cloned-to');};this.init($element,options);};$.fn.AutoClone=(function(options){return this.each(function(){(new $.AutoClone($(this),options));});});$.AutoClone.defaultOptions={};$("[data-action='clone'][data-type='src']").AutoClone();})(jQuery);(function($){$.AutoMove=function($element,options){$element.data('AutoMove',this);this.$currentObject=$element;this.key=null;this.init=function($element,options){this.options=$.extend({},$.AutoMove.defaultOptions,options);$(document).bind('enter-xs',$.proxy(function(){this.bpChange('xs')},this));$(document).bind('enter-sm',$.proxy(function(){this.bpChange('sm')},this));$(document).bind('enter-md',$.proxy(function(){this.bpChange('md')},this));$(document).bind('enter-lg',$.proxy(function(){this.bpChange('lg')},this));};this.bpChange=function(bp){var key=this.$currentObject.data('key');$("[data-action='move'][data-key='"+key+"']").each(function(){if($(this).attr("data-bp").indexOf(bp)==-1){$(this).attr({"data-type":"src"});}
else{$(this).attr({"data-type":"dest"});}});if($("[data-action='move'][data-key='"+key+"'][data-type='dest']").is(":empty")==true){$("[data-action='move'][data-key='"+key+"'][data-type='src']").trigger('moving-from');$("[data-action='move'][data-key='"+key+"'][data-type='dest']").trigger('moving-to');$("[data-action='move'][data-key='"+key+"'][data-type='src']").clone(true).appendTo($("[data-action='move'][data-key='"+key+"'][data-type='dest']")).prepend('<div></div>').find('> div:first-child').unwrap().remove();$("[data-action='move'][data-key='"+key+"'][data-type='src']").empty();$("[data-action='move'][data-key='"+key+"'][data-type='src']").trigger('moved-from');$("[data-action='move'][data-key='"+key+"'][data-type='dest']").trigger('moved-to');}
$("[data-action='move'][data-key='"+key+"']").removeAttr("data-type");};this.init($element,options);};$.fn.AutoMove=(function(options){return this.each(function(){(new $.AutoMove($(this),options));});});$.AutoMove.defaultOptions={};$("[data-action='move']").AutoMove();})(jQuery);(function($){$.BPEvents=function(options){this.bp=new Array();this.init=function(options){this.options=$.extend({},$.BPEvents.defaultOptions,options);if(window.matchMedia){this.bp['xs']=window.matchMedia('(max-width: 767px)');this.bp['sm']=window.matchMedia('(min-width: 768px) and (max-width: 959px)');this.bp['md']=window.matchMedia('(min-width: 960px) and (max-width: 1199px)');this.bp['lg']=window.matchMedia('(min-width: 1200px)');for(var key in this.bp){this.bp[key].addListener($.proxy(this.bpChange,this));if(this.bp[key].matches){$(document).trigger('enter-'+key);}}}};this.bpChange=function(media){var type=(media.matches)?'enter':'leave';$(document).trigger(type+'-'+this.getBP(media));};this.getBP=function(media){for(var key in this.bp){if(this.bp[key].media==media.media)return key;}};this.init(options);};$.fn.BPEvents=(function(options){(new $.BPEvents(options));});$.BPEvents.defaultOptions={};$.BPEvents();})(jQuery);
;;;